### ISSUE TITLE
fix casing for 'Gaia GPS' in banner

### ISSUE THREAD

**Issue by ashlibaldwin** [trailbehind/NG_Help_Center#15]
on main page of HC, it says 'GAIA GPS Help Center' but GAIA should be titlecase instead of all caps

**Comment by JimMargolis** [comment]
I didn't bother with a PR for this, but edited the code directly here: https://help.gaiagps.com/theming/editor/ea2b81f2-b1e5-49c0-953b-f8dfb4978ca4/templates/home_page.hbs

Should be all good now.
